### PR TITLE
Add capella-textual-editor

### PR DESCRIPTION
**Pull request by georgiana-ecobici**
Change-Id: Iffd7aebd520165e31644589ada1cba6c9fc3225c
Signed-off-by: Georgiana-Elena ECOBICI <georgiana-elena.ecobici@thalesgroup.com>

### CODE REVIEW

**Review by felixdo — COMMENTED** [review]
Nothing against this commit in particular but why do we need this repo-directory mapping at all? How confusing is that...? Why not use just the repository name?

**Comment by sandupostaru** [comment]
> 
> 
> Nothing against this commit in particular but why do we need this repo-directory mapping at all? How confusing is that...? Why not use just the repository name?

The directory names existed before this library was put into place (https://download.eclipse.org/capella/addons/). The mapping was introduced in order to keep the existing names. 

Nothing stops us from using the repository names directly if we decide on it. But we must move the existing products and update sites into their newest location. This might break existing builds though.

**Review by sandupostaru — APPROVED** [review]

**Comment by felixdo** [comment]
> The directory names existed before this library was put into place (https://download.eclipse.org/capella/addons/). The mapping was introduced in order to keep the existing names.

Not in this particular case though...

> Nothing stops us from using the repository names directly if we decide on it. But we must move the existing products and update sites into their newest location. This might break existing builds though.

Oh, suddenly we are concerned about breaking 3rd party builds that depend on our addons? Nice 👍 

I would just use symlinks, announce on the mailing list to remove them after a year, and use a sensible default... so we can deploy new addons without editing the library

**Comment by felixdo** [comment]
Or.. just not care at all, as I did for capella tools.. 
https://download.eclipse.org/capella/capella-tools/ (old)
https://download.eclipse.org/capella/addons/capella-tools/ (new)

It's not pretty, but hey....

BTW, the ultimate ultimate solution which should be targeted is to have a composite repo 
download.eclipse.org/capella/addons, which includes everything, and then who cares how many different sites are used within.,

**Pull request merged**
